### ISSUE TITLE
Mismatch : RuntimeError: Error(s) in loading state_dict for ResNet

### ISSUE THREAD

**Issue by Zhiying-Li-dot** [Ytchen981/CSA#2]
I followed the steps you wrote, training first and then changing the address of shapley.model_path to the trained weights file. But then I run python Shapley_softmax.py --config config/Shapley.yaml. and it reports the following error.

`RuntimeError: Error(s) in loading state_dict for ResNet:
	Missing key(s) in state_dict: "layer2.0.shortcut.0.weight", "layer2.0.shortcut.1.weight", "layer2.0.shortcut.1.bias", "layer2.0.shortcut.1.running_mean", "layer2.0.shortcut.1.running_var", "layer3.0.shortcut.0.weight", "layer3.0.shortcut.1.weight", "layer3.0.shortcut.1.bias", "layer3.0.shortcut.1.running_mean", "layer3.0.shortcut.1.running_var", "layer4.0.shortcut.0.weight", "layer4.0.shortcut.1.weight", "layer4.0.shortcut.1.bias", "layer4.0.shortcut.1.running_mean", "layer4.0.shortcut.1.running_var", "linear.weight", "linear.bias". 
	Unexpected key(s) in state_dict: "fc.weight", "fc.bias", "layer2.0.downsample.0.weight", "layer2.0.downsample.1.weight", "layer2.0.downsample.1.bias", "layer2.0.downsample.1.running_mean", "layer2.0.downsample.1.running_var", "layer2.0.downsample.1.num_batches_tracked", "layer3.0.downsample.0.weight", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.bias", "layer3.0.downsample.1.running_mean", "layer3.0.downsample.1.running_var", "layer3.0.downsample.1.num_batches_tracked", "layer4.0.downsample.0.weight", "layer4.0.downsample.1.weight", "layer4.0.downsample.1.bias", "layer4.0.downsample.1.running_mean", "layer4.0.downsample.1.running_var", "layer4.0.downsample.1.num_batches_tracked". 
	size mismatch for conv1.weight: copying a param with shape torch.Size([64, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).`

**Comment by Zhiying-Li-dot** [comment]
What should I do to solve this problem, I checked the code and the ResNet models used are all the same, i.e. ResNet18.

**Comment by Ytchen981** [comment]
It seems that the checkpoint you attempt to load is a checkpoint for the ResNet18 in torchvision.models where the first layer is a convolution with kernel size as 7, which is for Imagenet. As a conventional approach, the ResNet18 defined in model/resnet.py is a modification of ResNet18 for Cifar10, where the kernel size of the first convolution layer is set to be 3.  

In this repository, we use ResNet18 in torchvision.models for ImageNet and Tiny-Imagenet and use the modified ResNet18 in model/resnet.py for Cifar10. To solve the encountered problem, please make sure that you calculate shapley value on the same dataset that you train the model for and use the same structure.

You are welcome to pose more comments, if you have further questions.
